# Generated by Django 2.2.6 on 2019-10-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifyapp', '0002_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('user_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=50)),
                ('user_phone', models.CharField(max_length=50)),
                ('user_desc', models.CharField(max_length=50)),
            ],
        ),
    ]
